[package]
name = "lsm"
version = "0.1.0"
authors = ["Tuan Vuong <vanhtuan0409@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
bincode = "1.3.1"
